#!/usr/bin/env python3
import re, os, sys

GO_MAP_RE = re.compile(
    r"var\s+alphabet\s*=\s*map\[rune\]\[\]\[\]Point\s*\{(.*)\}", re.S
)
ENTRY_RE = re.compile(r"'([^']+)'\s*:\s*(\{\{\{.*?\}\}\})", re.S)
NUM_RE = re.compile(r"-?\d+(?:\.\d+)?")

src = open(
    sys.argv[1] if len(sys.argv) > 1 else "/home/kof/src/gomotor/gen.go",
    encoding="utf-8",
).read()
m = GO_MAP_RE.search(src)
assert m, "no alphabet map"


def parse_value(s):
    i = 0

    def skip():
        nonlocal i
        while i < len(s) and s[i].isspace():
            i += 1

    def num():
        nonlocal i
        skip()
        mm = NUM_RE.match(s, i)
        if not mm:
            raise ValueError(s[i : i + 10])
        i = mm.end()
        return float(mm.group())

    def item():
        nonlocal i
        skip()
        assert s[i] == "{"
        i += 1
        skip()
        if s[i] == "{":
            items = []
            while True:
                skip()
                if s[i] == "}":
                    i += 1
                    return items
                items.append(item())
                skip()
                if s[i] == ",":
                    i += 1
        else:
            x = num()
            skip()
            if s[i] == ",":
                i += 1
            y = num()
            skip()
            assert s[i] == "}"
            i += 1
            return (x, y)

    return item()


alphabet = {}
for key, val in ENTRY_RE.findall(m.group(1)):
    alphabet[key] = parse_value(val)

glyphs = sorted(alphabet.items())  # sort by codepoint

lines = []
lines.append(
    "/* GENERATED by tools/gen_gomfont.py from gomotor/gen.go (alphabet map). */"
)
lines.append("static const GfPt gf0[] = {{ (float)0, (float)0 }};")
point_defs = []
stroke_defs = []
glyph_entries = []
pindex = 0
for cp_str, strokes in glyphs:
    cp = ord(cp_str[0])
    # each stroke -> point array
    sarr_ptrs = []
    for si, stroke in enumerate(strokes):
        name = f"gfp{cp}_{si}"
        coords = ", ".join(f"{{(float){x:.1f},(float){y:.1f}}}" for x, y in stroke)
        n = len(stroke)
        if n == 0:
            point_defs.append(f"static const GfPt {name}[] = {{ (float)0,(float)0 }};")
        else:
            point_defs.append(f"static const GfPt {name}[] = {{ {coords} }};")
        sarr_ptrs.append(f"{{ {name}, {n} }}")
    sname = f"gfs{cp}"
    stroke_defs.append(
        f"static const GfStroke {sname}[] = {{ {', '.join(sarr_ptrs)} }};"
    )
    glyph_entries.append(f"    {{ 0x{cp:04X}u, {len(sarr_ptrs)}, {sname} }},")

lines += point_defs
lines.append("")
lines += stroke_defs
lines.append("")
lines.append("static const GfGlyph GF_HAS = { 0, 0, NULL };")
lines.append("")
lines.append("static const GfGlyph GF_GLYPHS[] = {")
lines += glyph_entries
lines.append("};")
lines.append("")

out = "\n".join(lines)
with open("/home/kof/src/gram/src/gomfont_data.c", "w", encoding="utf-8") as f:
    f.write(out)
print("glyphs:", len(glyphs))
