/* GENERATED by tools/gen_gomfont.py from gomotor/gen.go (alphabet map). */
static const GfPt gf0[] = {{ (float)0, (float)0 }};
static const GfPt gfp33_0[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)30.0} };
static const GfPt gfp33_1[] = { {(float)20.0,(float)45.0}, {(float)22.0,(float)45.0} };
static const GfPt gfp40_0[] = { {(float)30.0,(float)0.0}, {(float)10.0,(float)25.0}, {(float)30.0,(float)50.0} };
static const GfPt gfp41_0[] = { {(float)10.0,(float)0.0}, {(float)30.0,(float)25.0}, {(float)10.0,(float)50.0} };
static const GfPt gfp43_0[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp43_1[] = { {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0} };
static const GfPt gfp44_0[] = { {(float)20.0,(float)40.0}, {(float)15.0,(float)55.0} };
static const GfPt gfp45_0[] = { {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0} };
static const GfPt gfp46_0[] = { {(float)20.0,(float)45.0}, {(float)22.0,(float)45.0} };
static const GfPt gfp47_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp48_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0} };
static const GfPt gfp49_0[] = { {(float)10.0,(float)15.0}, {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp49_1[] = { {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp50_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp51_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp51_1[] = { {(float)40.0,(float)25.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp52_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0} };
static const GfPt gfp52_1[] = { {(float)30.0,(float)0.0}, {(float)30.0,(float)50.0} };
static const GfPt gfp53_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp54_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp55_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp56_0[] = { {(float)20.0,(float)25.0}, {(float)0.0,(float)25.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)20.0,(float)25.0}, {(float)0.0,(float)25.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)25.0} };
static const GfPt gfp57_0[] = { {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp58_0[] = { {(float)20.0,(float)15.0}, {(float)22.0,(float)15.0} };
static const GfPt gfp58_1[] = { {(float)20.0,(float)45.0}, {(float)22.0,(float)45.0} };
static const GfPt gfp60_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp61_0[] = { {(float)0.0,(float)15.0}, {(float)40.0,(float)15.0} };
static const GfPt gfp61_1[] = { {(float)0.0,(float)35.0}, {(float)40.0,(float)35.0} };
static const GfPt gfp62_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp63_0[] = { {(float)0.0,(float)15.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)20.0}, {(float)20.0,(float)30.0} };
static const GfPt gfp63_1[] = { {(float)20.0,(float)45.0}, {(float)22.0,(float)45.0} };
static const GfPt gfp65_0[] = { {(float)0.0,(float)50.0}, {(float)20.0,(float)0.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp65_1[] = { {(float)10.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp66_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)30.0,(float)0.0}, {(float)40.0,(float)12.0}, {(float)30.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp66_1[] = { {(float)30.0,(float)25.0}, {(float)40.0,(float)37.0}, {(float)30.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp67_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp68_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)30.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)30.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp69_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp69_1[] = { {(float)0.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp70_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp70_1[] = { {(float)0.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp71_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)25.0}, {(float)20.0,(float)25.0} };
static const GfPt gfp72_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp72_1[] = { {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp72_2[] = { {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0} };
static const GfPt gfp73_0[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp73_1[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp73_2[] = { {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp74_0[] = { {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp75_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp75_1[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp76_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp77_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)20.0,(float)25.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp78_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp79_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0} };
static const GfPt gfp80_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp81_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0} };
static const GfPt gfp81_1[] = { {(float)20.0,(float)30.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp82_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp82_1[] = { {(float)20.0,(float)25.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp83_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp84_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp84_1[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp85_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp86_0[] = { {(float)0.0,(float)0.0}, {(float)20.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp87_0[] = { {(float)0.0,(float)0.0}, {(float)10.0,(float)50.0}, {(float)20.0,(float)25.0}, {(float)30.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp88_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp88_1[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp89_0[] = { {(float)0.0,(float)0.0}, {(float)20.0,(float)25.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp89_1[] = { {(float)20.0,(float)25.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp90_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp91_0[] = { {(float)30.0,(float)0.0}, {(float)10.0,(float)0.0}, {(float)10.0,(float)50.0}, {(float)30.0,(float)50.0} };
static const GfPt gfp93_0[] = { {(float)10.0,(float)0.0}, {(float)30.0,(float)0.0}, {(float)30.0,(float)50.0}, {(float)10.0,(float)50.0} };
static const GfPt gfp95_0[] = { {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp123_0[] = { {(float)30.0,(float)0.0}, {(float)15.0,(float)15.0}, {(float)15.0,(float)35.0}, {(float)30.0,(float)50.0} };
static const GfPt gfp125_0[] = { {(float)15.0,(float)0.0}, {(float)30.0,(float)15.0}, {(float)30.0,(float)35.0}, {(float)15.0,(float)50.0} };
static const GfPt gfp193_0[] = { {(float)0.0,(float)50.0}, {(float)20.0,(float)0.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp193_1[] = { {(float)10.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp193_2[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp201_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp201_1[] = { {(float)0.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp201_2[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp205_0[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp205_1[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp211_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0} };
static const GfPt gfp211_1[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp218_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp218_1[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp221_0[] = { {(float)0.0,(float)0.0}, {(float)20.0,(float)25.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp221_1[] = { {(float)20.0,(float)25.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp221_2[] = { {(float)15.0,(float)-15.0}, {(float)25.0,(float)-5.0} };
static const GfPt gfp268_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp268_1[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp270_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)30.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)30.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp270_1[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp282_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp282_1[] = { {(float)0.0,(float)25.0}, {(float)30.0,(float)25.0} };
static const GfPt gfp282_2[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp327_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp327_1[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp344_0[] = { {(float)0.0,(float)50.0}, {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)40.0,(float)25.0}, {(float)0.0,(float)25.0} };
static const GfPt gfp344_1[] = { {(float)20.0,(float)25.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp344_2[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp352_0[] = { {(float)40.0,(float)0.0}, {(float)0.0,(float)0.0}, {(float)0.0,(float)25.0}, {(float)40.0,(float)25.0}, {(float)40.0,(float)50.0}, {(float)0.0,(float)50.0} };
static const GfPt gfp352_1[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp356_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp356_1[] = { {(float)20.0,(float)0.0}, {(float)20.0,(float)50.0} };
static const GfPt gfp356_2[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };
static const GfPt gfp366_0[] = { {(float)0.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0}, {(float)40.0,(float)0.0} };
static const GfPt gfp366_1[] = { {(float)15.0,(float)-10.0}, {(float)25.0,(float)-10.0}, {(float)25.0,(float)-20.0}, {(float)15.0,(float)-20.0}, {(float)15.0,(float)-10.0} };
static const GfPt gfp381_0[] = { {(float)0.0,(float)0.0}, {(float)40.0,(float)0.0}, {(float)0.0,(float)50.0}, {(float)40.0,(float)50.0} };
static const GfPt gfp381_1[] = { {(float)10.0,(float)-15.0}, {(float)20.0,(float)-5.0}, {(float)30.0,(float)-15.0} };

static const GfStroke gfs33[] = { { gfp33_0, 2 }, { gfp33_1, 2 } };
static const GfStroke gfs40[] = { { gfp40_0, 3 } };
static const GfStroke gfs41[] = { { gfp41_0, 3 } };
static const GfStroke gfs43[] = { { gfp43_0, 2 }, { gfp43_1, 2 } };
static const GfStroke gfs44[] = { { gfp44_0, 2 } };
static const GfStroke gfs45[] = { { gfp45_0, 2 } };
static const GfStroke gfs46[] = { { gfp46_0, 2 } };
static const GfStroke gfs47[] = { { gfp47_0, 2 } };
static const GfStroke gfs48[] = { { gfp48_0, 5 } };
static const GfStroke gfs49[] = { { gfp49_0, 3 }, { gfp49_1, 2 } };
static const GfStroke gfs50[] = { { gfp50_0, 6 } };
static const GfStroke gfs51[] = { { gfp51_0, 4 }, { gfp51_1, 3 } };
static const GfStroke gfs52[] = { { gfp52_0, 3 }, { gfp52_1, 2 } };
static const GfStroke gfs53[] = { { gfp53_0, 6 } };
static const GfStroke gfs54[] = { { gfp54_0, 6 } };
static const GfStroke gfs55[] = { { gfp55_0, 3 } };
static const GfStroke gfs56[] = { { gfp56_0, 10 } };
static const GfStroke gfs57[] = { { gfp57_0, 6 } };
static const GfStroke gfs58[] = { { gfp58_0, 2 }, { gfp58_1, 2 } };
static const GfStroke gfs60[] = { { gfp60_0, 3 } };
static const GfStroke gfs61[] = { { gfp61_0, 2 }, { gfp61_1, 2 } };
static const GfStroke gfs62[] = { { gfp62_0, 3 } };
static const GfStroke gfs63[] = { { gfp63_0, 5 }, { gfp63_1, 2 } };
static const GfStroke gfs65[] = { { gfp65_0, 3 }, { gfp65_1, 2 } };
static const GfStroke gfs66[] = { { gfp66_0, 6 }, { gfp66_1, 4 } };
static const GfStroke gfs67[] = { { gfp67_0, 4 } };
static const GfStroke gfs68[] = { { gfp68_0, 6 } };
static const GfStroke gfs69[] = { { gfp69_0, 4 }, { gfp69_1, 2 } };
static const GfStroke gfs70[] = { { gfp70_0, 3 }, { gfp70_1, 2 } };
static const GfStroke gfs71[] = { { gfp71_0, 6 } };
static const GfStroke gfs72[] = { { gfp72_0, 2 }, { gfp72_1, 2 }, { gfp72_2, 2 } };
static const GfStroke gfs73[] = { { gfp73_0, 2 }, { gfp73_1, 2 }, { gfp73_2, 2 } };
static const GfStroke gfs74[] = { { gfp74_0, 4 } };
static const GfStroke gfs75[] = { { gfp75_0, 2 }, { gfp75_1, 3 } };
static const GfStroke gfs76[] = { { gfp76_0, 3 } };
static const GfStroke gfs77[] = { { gfp77_0, 5 } };
static const GfStroke gfs78[] = { { gfp78_0, 4 } };
static const GfStroke gfs79[] = { { gfp79_0, 5 } };
static const GfStroke gfs80[] = { { gfp80_0, 5 } };
static const GfStroke gfs81[] = { { gfp81_0, 5 }, { gfp81_1, 2 } };
static const GfStroke gfs82[] = { { gfp82_0, 5 }, { gfp82_1, 2 } };
static const GfStroke gfs83[] = { { gfp83_0, 6 } };
static const GfStroke gfs84[] = { { gfp84_0, 2 }, { gfp84_1, 2 } };
static const GfStroke gfs85[] = { { gfp85_0, 4 } };
static const GfStroke gfs86[] = { { gfp86_0, 3 } };
static const GfStroke gfs87[] = { { gfp87_0, 5 } };
static const GfStroke gfs88[] = { { gfp88_0, 2 }, { gfp88_1, 2 } };
static const GfStroke gfs89[] = { { gfp89_0, 3 }, { gfp89_1, 2 } };
static const GfStroke gfs90[] = { { gfp90_0, 4 } };
static const GfStroke gfs91[] = { { gfp91_0, 4 } };
static const GfStroke gfs93[] = { { gfp93_0, 4 } };
static const GfStroke gfs95[] = { { gfp95_0, 2 } };
static const GfStroke gfs123[] = { { gfp123_0, 4 } };
static const GfStroke gfs125[] = { { gfp125_0, 4 } };
static const GfStroke gfs193[] = { { gfp193_0, 3 }, { gfp193_1, 2 }, { gfp193_2, 2 } };
static const GfStroke gfs201[] = { { gfp201_0, 4 }, { gfp201_1, 2 }, { gfp201_2, 2 } };
static const GfStroke gfs205[] = { { gfp205_0, 2 }, { gfp205_1, 2 } };
static const GfStroke gfs211[] = { { gfp211_0, 5 }, { gfp211_1, 2 } };
static const GfStroke gfs218[] = { { gfp218_0, 4 }, { gfp218_1, 2 } };
static const GfStroke gfs221[] = { { gfp221_0, 3 }, { gfp221_1, 2 }, { gfp221_2, 2 } };
static const GfStroke gfs268[] = { { gfp268_0, 4 }, { gfp268_1, 3 } };
static const GfStroke gfs270[] = { { gfp270_0, 6 }, { gfp270_1, 3 } };
static const GfStroke gfs282[] = { { gfp282_0, 4 }, { gfp282_1, 2 }, { gfp282_2, 3 } };
static const GfStroke gfs327[] = { { gfp327_0, 4 }, { gfp327_1, 3 } };
static const GfStroke gfs344[] = { { gfp344_0, 5 }, { gfp344_1, 2 }, { gfp344_2, 3 } };
static const GfStroke gfs352[] = { { gfp352_0, 6 }, { gfp352_1, 3 } };
static const GfStroke gfs356[] = { { gfp356_0, 2 }, { gfp356_1, 2 }, { gfp356_2, 3 } };
static const GfStroke gfs366[] = { { gfp366_0, 4 }, { gfp366_1, 5 } };
static const GfStroke gfs381[] = { { gfp381_0, 4 }, { gfp381_1, 3 } };

static const GfGlyph GF_HAS = { 0, 0, NULL };

static const GfGlyph GF_GLYPHS[] = {
    { 0x0021u, 2, gfs33 },
    { 0x0028u, 1, gfs40 },
    { 0x0029u, 1, gfs41 },
    { 0x002Bu, 2, gfs43 },
    { 0x002Cu, 1, gfs44 },
    { 0x002Du, 1, gfs45 },
    { 0x002Eu, 1, gfs46 },
    { 0x002Fu, 1, gfs47 },
    { 0x0030u, 1, gfs48 },
    { 0x0031u, 2, gfs49 },
    { 0x0032u, 1, gfs50 },
    { 0x0033u, 2, gfs51 },
    { 0x0034u, 2, gfs52 },
    { 0x0035u, 1, gfs53 },
    { 0x0036u, 1, gfs54 },
    { 0x0037u, 1, gfs55 },
    { 0x0038u, 1, gfs56 },
    { 0x0039u, 1, gfs57 },
    { 0x003Au, 2, gfs58 },
    { 0x003Cu, 1, gfs60 },
    { 0x003Du, 2, gfs61 },
    { 0x003Eu, 1, gfs62 },
    { 0x003Fu, 2, gfs63 },
    { 0x0041u, 2, gfs65 },
    { 0x0042u, 2, gfs66 },
    { 0x0043u, 1, gfs67 },
    { 0x0044u, 1, gfs68 },
    { 0x0045u, 2, gfs69 },
    { 0x0046u, 2, gfs70 },
    { 0x0047u, 1, gfs71 },
    { 0x0048u, 3, gfs72 },
    { 0x0049u, 3, gfs73 },
    { 0x004Au, 1, gfs74 },
    { 0x004Bu, 2, gfs75 },
    { 0x004Cu, 1, gfs76 },
    { 0x004Du, 1, gfs77 },
    { 0x004Eu, 1, gfs78 },
    { 0x004Fu, 1, gfs79 },
    { 0x0050u, 1, gfs80 },
    { 0x0051u, 2, gfs81 },
    { 0x0052u, 2, gfs82 },
    { 0x0053u, 1, gfs83 },
    { 0x0054u, 2, gfs84 },
    { 0x0055u, 1, gfs85 },
    { 0x0056u, 1, gfs86 },
    { 0x0057u, 1, gfs87 },
    { 0x0058u, 2, gfs88 },
    { 0x0059u, 2, gfs89 },
    { 0x005Au, 1, gfs90 },
    { 0x005Bu, 1, gfs91 },
    { 0x005Du, 1, gfs93 },
    { 0x005Fu, 1, gfs95 },
    { 0x007Bu, 1, gfs123 },
    { 0x007Du, 1, gfs125 },
    { 0x00C1u, 3, gfs193 },
    { 0x00C9u, 3, gfs201 },
    { 0x00CDu, 2, gfs205 },
    { 0x00D3u, 2, gfs211 },
    { 0x00DAu, 2, gfs218 },
    { 0x00DDu, 3, gfs221 },
    { 0x010Cu, 2, gfs268 },
    { 0x010Eu, 2, gfs270 },
    { 0x011Au, 3, gfs282 },
    { 0x0147u, 2, gfs327 },
    { 0x0158u, 3, gfs344 },
    { 0x0160u, 2, gfs352 },
    { 0x0164u, 3, gfs356 },
    { 0x016Eu, 2, gfs366 },
    { 0x017Du, 2, gfs381 },
};
